/// Hand-pruned ScaffoldEscrow ABI used by the dashboard. Generated by
/// `forge inspect ScaffoldEscrow abi --json` and trimmed to the methods +
/// events the UI actually consumes.
export const SCAFFOLD_ESCROW_ABI = [
  {
    type: 'function',
    name: 'jobIdFor',
    stateMutability: 'pure',
    inputs: [
      { name: 'buyer', type: 'address' },
      { name: 'nonce', type: 'uint256' },
    ],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'initialize',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'nonce', type: 'uint256' },
      { name: 'worker', type: 'address' },
      { name: 'arbiter', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'budget', type: 'uint256' },
      { name: 'deadline', type: 'uint64' },
      { name: 'qualityThresholdBps', type: 'uint16' },
      { name: 'checkpointCount', type: 'uint8' },
      { name: 'weights', type: 'uint16[16]' },
      { name: 'specHash', type: 'bytes32' },
    ],
    outputs: [{ name: 'jobId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'releaseStreamed',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'bytes32' },
      { name: 'checkpointIndex', type: 'uint8' },
      { name: 'scoreBps', type: 'uint16' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPause',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'bytes32' },
      { name: 'paused', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'refundBuyer',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalizeJob',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getJob',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'bytes32' }],
    outputs: [
      { name: 'buyer', type: 'address' },
      { name: 'worker', type: 'address' },
      { name: 'arbiter', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'budget', type: 'uint256' },
      { name: 'released', type: 'uint256' },
      { name: 'deadline', type: 'uint64' },
      { name: 'qualityThresholdBps', type: 'uint16' },
      { name: 'checkpointCount', type: 'uint8' },
      { name: 'deposited', type: 'bool' },
      { name: 'paused', type: 'bool' },
      { name: 'finalized', type: 'bool' },
      { name: 'specHash', type: 'bytes32' },
    ],
  },
  {
    type: 'function',
    name: 'getCheckpointProgress',
    stateMutability: 'view',
    inputs: [
      { name: 'jobId', type: 'bytes32' },
      { name: 'idx', type: 'uint8' },
    ],
    outputs: [
      { name: 'weight', type: 'uint16' },
      { name: 'releasedBps', type: 'uint16' },
    ],
  },
  {
    type: 'event',
    name: 'JobInitialized',
    inputs: [
      { name: 'jobId', type: 'bytes32', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'worker', type: 'address', indexed: true },
      { name: 'arbiter', type: 'address', indexed: false },
      { name: 'budget', type: 'uint256', indexed: false },
      { name: 'deadline', type: 'uint64', indexed: false },
      { name: 'qualityThresholdBps', type: 'uint16', indexed: false },
      { name: 'specHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ReleaseStreamed',
    inputs: [
      { name: 'jobId', type: 'bytes32', indexed: true },
      { name: 'checkpoint', type: 'uint8', indexed: true },
      { name: 'fromBps', type: 'uint16', indexed: false },
      { name: 'toBps', type: 'uint16', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const;
